apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: usersecret
  namespace: authentik
stringData:
  name: usersecret-BBB
---
apiVersion: cscg.live/v1alpha1
kind: Blueprint
metadata:
  name: usersecret-bp
  namespace: authentik
spec:
  version: 1
  contextFrom:
    - secretRef:
        name: usersecret
  entries:
    - identifiers:
        username: usersecret
      model: authentik_core.user
      attrs:
        name:
          $Context: name
        is_active: true
        email: usersecret@mail.com
        type: external
